# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_close_open_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
