# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_add_closed_to_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deep_num_replies',
            field=models.IntegerField(default=0),
        ),
    ]
