# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-31 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_comment_reply_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='candidate_type',
            field=models.IntegerField(default=0),
        ),
    ]
