# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-31 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_article_candidate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='candidate_reason',
            field=models.TextField(null=True),
        ),
    ]
