# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-31 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_commentauthor_first_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentauthor',
            name='first_comment',
        ),
        migrations.AddField(
            model_name='article',
            name='first_comment',
            field=models.TextField(null=True),
        ),
    ]
