# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-14 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20170831_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='summary_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='summary_likes',
            field=models.IntegerField(default=0),
        ),
    ]
